services:
  - type: web
    name: fitness-analyzer
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 --bind :5000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
